services:
  gateway:
    image: gateway
    ports:
      - '3000:3000'
    environment:
      DB_SERVICE_ADDR: db-service
      AUTH_SERVICE_ADDR: auth-service
    networks:
      - bog-api-net
    depends_on:
      - auth-service

  auth-service:
    image: auth-service
    ports:
      - '50052:50052'
    environment:
      AUTH_SERVICE_ADDR: auth-service
      DB_SERVICE_ADDR: db-service
    networks:
      - bog-api-net
    depends_on:
      - db-service

  db-service:
    image: db-service
    ports:
      - '50053:50053'
    environment:
      AUTH_SERVICE_ADDR: auth-service
      DB_SERVICE_ADDR: db-service
      DATABASE_URL: postgresql://user:password@db
    networks:
      - bog-api-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    networks:
      - bog-api-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user']
      interval: 2s
      timeout: 5s
      retries: 10

networks:
  bog-api-net:
    driver: bridge
