services:
  gateway:
    build:
      dockerfile: Dockerfile.dev
      target: gateway-dev
    volumes:
      - ./packages/api-gateway:/app/packages/api-gateway
      - ./packages/proto:/app/packages/proto
    ports:
      - '3000:3000'
    entrypoint: yarn start:dev
    environment:
      DB_SERVICE_ADDR: db-service
      AUTH_SERVICE_ADDR: auth-service
    networks:
      - bog-api-net
    depends_on:
      - auth-service

  auth-service:
    build:
      dockerfile: Dockerfile.dev
      target: auth-service-dev
    volumes:
      - ./packages/auth-service:/app/packages/auth-service
      - ./packages/proto:/app/packages/proto
    ports:
      - '50052:50052'
    entrypoint: yarn start:dev
    environment:
      AUTH_SERVICE_ADDR: auth-service
      DB_SERVICE_ADDR: db-service
    networks:
      - bog-api-net
    depends_on:
      - db-service

  db-service:
    build:
      dockerfile: Dockerfile.dev
      target: db-service-dev
    volumes:
      - ./packages/db-service:/app/packages/db-service
      - ./packages/proto:/app/packages/proto
    ports:
      - '50053:50053'
    entrypoint: ./entrypoint.sh
    environment:
      AUTH_SERVICE_ADDR: auth-service
      DB_SERVICE_ADDR: db-service
      DATABASE_URL: postgresql://user:password@db
    networks:
      - bog-api-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    networks:
      - bog-api-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bog-api-net:
    driver: bridge
