services:
  api-gateway:
    extends:
      file: docker-compose-dev.yml
      service: api-gateway
    volumes:
      - ./packages/api-gateway:/app/packages/api-gateway
      - /app/packages/api-gateway/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/api-gateway/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  auth-service:
    extends:
      file: docker-compose-dev.yml
      service: auth-service
    volumes:
      - ./packages/auth-service:/app/packages/auth-service
      - /app/packages/auth-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/auth-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  db-service:
    extends:
      file: docker-compose-dev.yml
      service: db-service
    volumes:
      - ./packages/db-service:/app/packages/db-service
      - /app/packages/db-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/db-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  db:
    extends:
      file: docker-compose-dev.yml
      service: db
