name: Format & Lint
on: [pull_request]

jobs:
  lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '24.4'

      - name: Install
        run: yarn install --frozen-lockfile
        id: install

      - name: Run prettier
        run: yarn format:check

      - name: Run ESLint
        run: yarn lint
        # Always run the linter, even if prettier failed
        if: ${{ steps.install.outcome == 'success' }}
